name: QA Delivery Pipeline E2E

on:
  push:
    branches: [ main ]

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout do Código
      uses: actions/checkout@v4

    - name: 🟢 Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: 🌐 Instalar Chrome Manualmente
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: 📦 Instalar Dependências
      run: npm install

    - name: 🕵️‍♂️ Rodar Testes (Modo Headless Moderno)
      run: node tests/checkout-test.js
