name: QA Delivery Pipeline E2E

on:
  push:
    branches: [ main ]

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout do Código
      uses: actions/checkout@v4

    - name: 🟢 Instalar Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: "24"

    - name: 📦 Instalar Dependências
      run: npm install

    - name: 🕵️‍♂️ Rodar Testes (Headless)
      run: node tests/checkout-test.js
